### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Alexey-Melikov** [Alexey-Melikov/ono-tebe-nado#2]

**Comment by Alexey-Melikov** [comment]
### visually

- [ ] Учтены особенности поведения интерактивных элементов в состояниях :focus и :focus-visible. Например, в состоянии :focus-visible у элементов формы лейбл обводится, а в состоянии :focus — не обводится.
- [ ] Состояния выбранных чекбоксов реализованы через псевдоэлементы.
- [ ] Все элементы доступны при навигации с клавиатуры, они визуально выделены при работе с ними.
- [ ] Подчеркивание у кнопок и чекбоксов появляется при наведении на всю активную зону (включая сам чекбокс), а не только на текст.
- [ ] В элементах формы при необходимости используются inherit или currentColor.
- [ ] Для предсказуемого поведения инпутов в разных браузерах использован appearance: none;.
- [ ] Вместо overflow: scroll использован overflow: auto, чтобы не отображался ненужный скролл.
- [ ] Вид курсора меняется при наведении на интерактивные элементы.
- [ ] Для наилучшего позиционирования изображения при задании свойства object-fit задаётся также подходящее значение свойства object-position.
- [ ] Для стилизации интерактивных элементов используется outline, а не border (outline не влияет на размеры элемента в потоке).
